use conveniomysql;

select 'Dropando tabela de Pagamentos OBTV' AS '';

DROP TABLE IF EXISTS PAGAMENTO_OBTV;

select 'Criando tabela de Pagamentos OBTV' AS '';

CREATE TABLE PAGAMENTO_OBTV (
ANO_CONVENIO			int(4)		NOT NULL,
NR_CONVENIO			int(6)		NOT NULL,
TX_MODALIDADE			varchar(20)	NOT NULL,
TX_SITUACAO			varchar(50)	NOT NULL,
NM_BANCO_CONVENIO		varchar(30)	NOT NULL,
CD_AGENCIA_CONVENIO		varchar(4)	NOT NULL,
NR_CONTA_CORRENTE_CONVENIO	varchar(10)	NOT NULL,
TX_SITUACAO_CONTA_CORRENTE	varchar(30)	NOT NULL,
CD_ORGAO_CONCEDENTE		int(5)		NOT NULL,
NM_ORGAO_CONCEDENTE		varchar(60)	NOT NULL,
CD_IDENT_CONVENENTE		varchar(14)	NOT NULL,
NM_IDENT_CONVENENTE		varchar(132)	NOT NULL,
TX_ESFERA_ADM_CONVENENTE	varchar(40)	NOT NULL,
NM_MUNICIPIO_CONVENENTE		varchar(40)	NOT NULL,
UF_CONVENENTE			char(2)		NOT NULL,
TX_REGIAO_CONVENENTE		varchar(12)	NOT NULL,
IN_PAGAMENTO_PARCIAL_SN		char(1)		NOT NULL,
NR_MOVIMENTACAO_FINANCEIRA	varchar(7)	NOT NULL,
NR_OBTV_SIAFI			varchar(12)	NOT NULL,
TX_TIPO_MOVIMENTACAO		varchar(25)	NOT NULL,
TX_SITUACAO_MOVIMENTACAO	varchar(40)	NOT NULL,
DT_INCLUSAO_MOV_FINANCEIRA	date	,
DT_AUT_GESTOR_FINANCEIRO	date	,
CPF_GESTOR_FINANCEIRO		varchar(11)	NOT NULL,
NM_GESTOR_FINANCEIRO		varchar(60)	NOT NULL,
DT_AUT_ORDENADOR_DESPESA	date	,
CPF_ORDENADOR_DESPESA		varchar(11)	NOT NULL,
NM_ORDENADOR_DESPESA		varchar(60)	NOT NULL,
DT_CANC_MOV_FINANCEIRA		date	,
NM_EVENTO			varchar(25)	NOT NULL,
NM_RESPONSAVEL_EVENTO		varchar(60)	NOT NULL,
NR_OBTV_CANCELAMENTO		varchar(12)	NOT NULL,
VL_PAGAMENTO			float(18,2)	NOT NULL,
ID_CONVENIO			int(6)		NOT NULL,
ID_DOCLIQUIDACAO 		int(7)		NOT NULL );

