use conveniomysql;

select 'Dropando tabela de Programas' AS '';

DROP TABLE IF EXISTS PROGRAMAS;

select 'Criando tabela de Programas' AS '';

CREATE TABLE PROGRAMAS (
CD_PROGRAMA            varchar(13) NOT NULL ,
NM_PROGRAMA            varchar(255) NOT NULL ,
TX_ACAO_PPA            varchar(8) NOT NULL ,
TX_DESCRICAO_PROGRAMA  varchar(250) NOT NULL ,
TX_SITUACAO_PROGRAMA   varchar(15) NOT NULL ,
CD_ORG_SUPERIOR        int(5)  NOT NULL ,
CD_ORG_CONCEDENTE      int(5) NOT NULL ,
DT_DISPONIBILIZACAO    date ,
ANO_DISPONIBILIZACAO   int(4) NOT NULL ,
MES_DISPONIBILIZACAO   int(2) NOT NULL ,
DT_INC_VIGENCIA        date ,
ANO_INC_VIGENCIA       int(4) NOT NULL ,
MES_INC_VIGENCIA       int(2) NOT NULL ,
DT_FIM_VIGENCIA        date ,
ANO_FIM_VIGENCIA       int(4) NOT NULL ,
MES_FIM_VIGENCIA       int(2) NOT NULL ,
CD_MANDATARIA          int(5) NOT NULL ,
NM_MANDATARIA          varchar(40) NOT NULL ,
CD_EXECUTOR            int(5) NOT NULL ,
IN_CRITERIO_SELECAO    char(1)  NOT NULL ,
IN_CHAMA_PUBLICO       char(1) NOT NULL ,
IN_REQUER_BENS_SERV    char(1) NOT NULL ,
IN_REQUER_CRONO_DESEMB char(1) NOT NULL ,
IN_ACEITA_PROP_SEM_CADASTRO char(1) NOT NULL ,
IN_REQUER_PLANO_TRABALHO char(1) NOT NULL ,
IN_EMENDA_PARLAMENTAR  char(1) NOT NULL ,
ID_PROGRAMA_CONVENIO   int(5) NOT NULL ,
QT_PROPOSTA            int(6) NOT NULL ,
QT_CONVENIO            int(6) NOT NULL );

