use conveniomysql;

select 'Dropando tabela de Emendas Parlamentares por Propostas' AS '';

DROP TABLE IF EXISTS PROPOSTAS_EMENDAP;

select 'Criando tabela de Emendas Parlamentares por Propostas' AS '';

CREATE TABLE PROPOSTAS_EMENDAP ( 
ANO_PROPOSTA			int(4)		not null,
NR_PROPOSTA			varchar(6)	not null,
ANO_CONVENIO			int(4)		not null,
NR_CONVENIO			varchar(6)	not null,
TX_MODALIDADE			varchar(40)	not null,
TX_SITUACAO			varchar(80)	not null,
TX_SUBSITUACAO			varchar(40)	not null,
CD_PROGRAMA			varchar(13)	not null,
CD_ACAO_PROGRAMA		varchar(8)	not null,
NM_PROGRAMA			varchar(250)	not null,
CD_ORGAO_SUPERIOR		int(5)		not null,
NM_ORGAO_SUPERIOR		varchar(70)	not null,
CD_ORGAO_CONCEDENTE		int(5)		not null,
NM_ORGAO_CONCEDENTE		varchar(70)	not null,
CD_IDENTIF_PROPONENTE		varchar(14)	not null,
NM_PROPONENTE			varchar(150)	not null,
TX_ESFERA_ADM_PROPONENTE	varchar(40)	not null,
TX_REGIAO_PROPONENTE		varchar(12)	not null,
UF_PROPONENTE			char(2)		not null,
NM_MUNICIPIO_PROPONENTE		varchar(40)	not null,
DT_PROPOSTA			date	 , 	
DT_INICIO_VIGENCIA		date	 , 	
DT_FIM_VIGENCIA			date	 , 	
DT_ASSINATURA			date	 , 
ANO_ASSINATURA			int(4)		not null,
MES_ASSINATURA			int(2)		not null,
DT_PUBLICACAO			date	 , 
VL_GLOBAL			float(18,2)	not null,
VL_REPASSE			float(18,2)	not null,
VL_REPASSE_EXERC_ATUAL		float(18,2)	not null,
VL_CONTRAPARTIDA		float(18,2)	not null,
VL_CONTRAPARTIDA_FINANC		float(18,2)	not null,
VL_CONTRAPARTIDA_BENS_SERV	float(18,2)	not null,
TX_QUALIFIC_PROPONENTE		varchar(40)	not null,
IN_PARECER_GESTOR_SN		char(1)		not null,
IN_PARECER_JURIDICO_SN		char(1)		not null,
IN_PARECER_TECNICO_SN		char(1)		not null,
NM_RESPONS_PROPONENTE		varchar(80)	not null,
CD_RESPONS_PROPONENTE		varchar(11)	not null,
NM_RESPONS_CONCEDENTE		varchar(80)	not null,
CD_RESPONS_CONCEDENTE		varchar(11)	not null,
NM_BANCO			varchar(40)	not null,
TX_OBJETO_CONVENIO		varchar(255)	not null,
TX_JUSTIFICATIVA		varchar(255)	not null,
NR_CNPJ_PROPONENTE_EMENDA	varchar(14)	not null,
NR_EMENDA_PARLAMENTAR		varchar(8)	not null,
NM_PROPONENTE_EMENDA		varchar(150)	not null,
VL_REPASSE_EMENDA		float(18,2)	not null,
ID_PROPOSTA			int(7)		not null,
ID_CONVENIO			int(6)		not null,
ID_PROP_PROGRAMA		int(6) 		not null );	

